const FETCH_E_MODIFICA = "FETCH DATA";
const DELETE_ITEM = "DELETE ITEM";
const AUMENTA_QTY = "ADD QTY";
const DIMINUISCI_QTY = "DIM QTY";
const SVUOTA_CARRELLO = "REMOVE ALL";
const COSTO_TOTALE = "SOMMA";
const CONTATORE = "CONTATORE";

export {
  FETCH_E_MODIFICA,
  DELETE_ITEM,
  AUMENTA_QTY,
  DIMINUISCI_QTY,
  SVUOTA_CARRELLO,
  CONTATORE,
  COSTO_TOTALE,
};
