const DELETE_ITEM = "DELETE ITEM";
const AUMENTA_QTY = "ADD QTY";
const DIMINUISCI_QTY = "DIM QTY";
const SVUOTA_CARRELLO = "REMOVE ALL";
const COSTO_TOTALE = "SOMMA";
const CONTATORE = "CONTATORE";
const DATA_FETCHING_STARTED = "DATA_FETCHING_STARTED";
const DATA_FETCHING_FAILED = "DATA_FETCHING_FAILED";
const DATA_FETCHING_SUCCESS = "DATA_FETCHING_SUCCESS";

export {
  DATA_FETCHING_STARTED,
  DATA_FETCHING_FAILED,
  DATA_FETCHING_SUCCESS,
  DELETE_ITEM,
  AUMENTA_QTY,
  DIMINUISCI_QTY,
  SVUOTA_CARRELLO,
  CONTATORE,
  COSTO_TOTALE,
};
